RELAXED_MUSCLE_LENGTH_ONE = 12.0  # in cm
RELAXED_MUSCLE_LENGTH_TWO = 13.0  # in cm
ADDITIONAL_STRETCH_LENGTH = 6 # in cm

# Bayesian Optimization
SEED = 37
NUM_INITIAL_POINTS = 1
NUM_NEW_CANDIDATES = 1
