from __future__ import annotations
# muscles
MIN_STRETCHED_MUSCLE_LENGTH_ONE = 20.0  # in cm
MAX_STRETCHED_MUSCLE_LENGTH_ONE = 30.0  # in cm
MIN_STRETCHED_MUSCLE_LENGTH_TWO = 20.0  # in cm
MAX_STRETCHED_MUSCLE_LENGTH_TWO = 30.0  # in cm

# Bayesian Optimization
SEED = 37

NUM_INITIAL_POINTS = 1
NUM_ITERATIONS = 10

NUM_NEW_CANDIDATES = 1
